# Generated by Django 5.2.3 on 2025-06-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cybervigilance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cybervigilancetest',
            old_name='answers',
            new_name='responses',
        ),
    ]
